
import Navbar from "@/components/Navbar";
import "./globals.css";

import { Poppins } from 'next/font/google';
import Footer from "@/components/Footer";
import Header from "@/components/Header";

const poppins = Poppins({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: "Exclusive",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.className}>

      <body className="overflow-x-hidden">
        <Header />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}


